### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by LarsFredrikHolstTry** [LarsFredrikHolstTry/bawser#18]
Vi trenger en skisse for alerts, eksempel:
![image](https://user-images.githubusercontent.com/29153280/208230949-90613605-fc17-4b2f-9f9d-fd35683b99dc.png)

**Comment by Cobrazking** [comment]
Tenker i grunn at disse alert boksene gjør jobben? Kanskje vi må tilpasse fargene litt bare :)
