### ISSUE TITLE
Start-guide

### ISSUE THREAD

**Issue by LarsFredrikHolstTry** [LarsFredrikHolstTry/bawser#23]
Er en start-guide noe vi skal prioritere? Altså at en helt ny spiller kun får tilgang til 1 og 1 funksjon, f.eks får brukeren etter første innlogging kun mulighet til å legge penger i banken og får da forklart at dette er for å unngå å bli utpresset for penger, for så å få tilgang til kriminalitet hvor han må utføre 5 krim, (ventetiden på de første 5 kriminalitetene kan være på f.eks 10 sekund for å få brukeren i gang.

Vet ikke helt om dette er en god eller dårlig idé så gjerne kom med innvendinger <3

**Comment by Cobrazking** [comment]
Ofte føler jeg at sånne guider er litt overflødige og kjedelige. Tenker at mye kan løses med "oppdrag" som får spillerne igang med spillet. Learning by doing. 

Kanskje vi heller får linke godt til oppdrag for de ny brukerne som ikke har startet på oppdrag. 

Eksempelvis så kan f.eks en varselboks vises -> som linker til første oppdrag og ikke går helt bort før man har gjennomført oppdraget.

**Comment by LarsFredrikHolstTry** [comment]
Enig, vi kan heller legge opp oppdragene slik at man får en "guide" via dem

**Comment by LarsFredrikHolstTry** [comment]
Legger heller opp oppgaver for å få brukeren i gang.
